
HEAD /suplementos

DELETE /suplementos

GET /suplementos/_search
{
  "query": {
    "match_all": {}
  }
}


POST /suplementos/_search
{
  "from": 0,      
  "size": 50,
  "query": {
    "multi_match": {
      "query": "hipercalorico",
      "fields": ["titulo^5", "especificacao^1", "marca^5", "especificacao_rota^5"]
    }
  }
}


POST /suplementos/_search
{
  "from": 0,      
  "size": 50,
  "query": {
    "multi_match": {
      "query": "Mass titanium refil",
      "fields": ["titulo^5", "especificacao^1", "marca^5", "especificacao_rota^5"]
    }
  },
  "sort": [
    {
      "quantidade": "desc"
    }
  ]
}

POST /suplementos/_search
{
  "from": 0,      
  "size": 50,
  "query": {
    "multi_match": {
      "query": "kit 2x",
      "fields": ["titulo^3", "especificacao^1", "marca^5", "especificacao_rota^5"]
    }
  }
}


POST /suplementos/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "whey protein",
            "fields": ["titulo^3", "especificacao^1", "marca^5", "especificacao_rota^5"]
          }
        }
      ]
    }
  },
  "sort": [
    {
      "quantidade": "asc"
    }
  ]
}

POST /suplementos/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "query": "creatina",
            "fields": ["titulo^3", "especificacao^1", "marca^5", "especificacao_rota^5"]
          }
        }
      ],
      "filter": {
        "range": {
          "quantidade": {
            "gte": 100,
            "lt": 2000
          }
        }
      }
    }
  },
  "sort": [
    {
      "preco_qnt": "asc"
    }
  ]
}

