
def get_synonyms(word_list):
    return [sublist for sublist in word_list if len(sublist) > 1]

BLACK_LIST = [
    'regata',
    'camiseta',
    'coqueteleira',
    'mochila',
    'garraf',
    'bone',
    'marmita',
    'marmiteira',
    'galao',
    'baby look',
    'mascara',
    'porta capsulas',
    'shoulder bag',
    'frisbee',
    'bottle',
    'shorts',
    'jaqueta',
    'calça',
    'legging',
    'blusa',
    'top dux',
    'viseira',
    'bermuda'
]

WORD_LIST_SUPLEMENTO = [['whey'],
 ['protein', 'proteina', 'proteica'],
 ['fibras'],
 ['beta alanina', 'betalanina', 'alanina'],
 ['hair', 'cabelo'],
 ['nail', 'unha'],
 ['antioxidantes'],
 ['concentrado'],
 ['iso', 'isolado', 'isolate'],
 ['hidrolisado'],
 ['albumina'],
 ['barrinha', 'barra', 'bar'],
 ['colageno', 'colagen'],
 ['chocolate'],
 ['wafer', 'bolacha', 'biscoito'],
 ['blend', 'mistura'],
 ['veg', 'vegan', 'vegano', 'vegie', 'vegana'],
 ['rice', 'arroz'],
 ['ervilha', 'pea'],
 ['crisp'],
 ['soy', 'soja'],
 ['nuts'],
 ['alfajor'],
 ['egg', 'ovo'],
 ['caseinato'],
 ['calcio'],
 ['verisol'],
 ['zinco'],
 ['creatina', 'creatine', 'creatin'],
 ['monohidratada'],
 ['glutamin', 'glutamina', 'lglutamina'],
 ['arginin', 'arginine', 'arginina'],
 ['bcaa', 'bca'],
 ['hmb', 'hydroxymethylbutyrate'],
 ['carnitin', 'carnitina', 'lcarnitina'],
 ['aminoacido'],
 ['triptofano'],
 ['taurina'],
 ['maca peruana'],
 ['leucin', 'leucine', 'lleucine'],
 ['mass', 'massa', 'hipercalorico'],
 ['malto', 'dextrina', 'maltodextrina'],
 ['frutose'],
 ['dextrose', 'maltodextrose'],
 ['waxy maize', 'amido de milho'],
 ['batata doce'],
 ['dribose'],
 ['curcuma', 'acafrao'],
 ['coco'],
 ['oleo'],
 ['zinco'],
 ['melatonina'],
 ['psyllium'],
 ['transresveratrol'],
 ['testofen'],
 ['cha'],
 ['astaxantina'],
 ['zeaxantina'],
 ['cafein', 'cafe', 'cafeina', 'coffe', 'caffe', 'coffee'],
 ['cafe verde'],
 ['termogenico'],
 ['pretreino', 'workout', 'pretrein', 'preworkout', 'pre workout'],
 ['biotina'],
 ['hialuronico'],
 ['optimsm'],
 ['palatinose'],
 ['levagen'],
 ['fosfatidilserina'],
 ['acetil', 'nacetil'],
 ['cistein', 'lcisteina'],
 ['linhaca'],
 ['primula'],
 ['borragem'],
 ['krill'],
 ['peixe', 'dha', 'omega 3'],
 ['laranja'],
 ['cromo'],
 ['resveratrol'],
 ['zinco'],
 ['betacaroteno'],
 ['cartamo'],
 ['quitosana'],
 ['propolis'],
 ['lecitina'],
 ['melatonina'],
 ['multivitaminico', 'polivitaminico'],
 ['zma'],
 ['magnesio'],
 ['coco'],
 ['chia'],
 ['cromo'],
 ['picolinato'],
 ['spirulina'],
 ['picolinato'],
 ['alho'],
 ['beauty', 'beleza'],
 ['skin', 'pele'],
 ['imune', 'imunidade'],
 ['uva'],
 ['semente'],
 ['antiox'],
 ['espirulina'],
 ['gengibre'],
 ['tempero'],
 ['xylitol'],
 ['vit', 'vitamina', 'vitamin'],
 ['pasta de amendoim'],
 ['cha verde'],
 ['coenzima q10', 'vitamina q10'],
 ['vitamina a'],
 ['complexo b', 'vitamina b'],
 ['vitamina b1', 'tiamina'],
 ['vitamina b2', 'riboflavina'],
 ['vitamina b3', 'niacina'],
 ['vitamina b5', 'pantotenico'],
 ['vitamina b6', 'piridoxina'],
 ['vitamina b7', 'biotina'],
 ['vitamina b9', 'folico'],
 ['vitamina b12', 'cobalamina'],
 ['vitamina c', 'ascorbico'],
 ['vitamina d', 'calciferol'],
 ['vitamina e', 'tocoferol'],
 ['vitamina k', 'filoquinona'],
 ['vitamina k1', 'fitoquinona'],
 ['vitamina k2', 'menaquinona'],
 ['vitamina k7', 'mk7'],
 ['vitamina j', 'lipoico'],
 ['vitamina l1'],
 ['vitamina l2'],
 ['vitamina m'],
 ['vitamina o'],
 ['vitamina p', 'bioflavonoides'],
 ['vitamina t', 'bioflavonoides'],
 ['vitamina b4', 'adenina'],
 ['vitamina b8', 'inositol'],
 ['vitamina b10', 'paraaminobenzoico'],
 ['vitamina b11', 'salicilico'],
 ['vitamina b13', 'orotico'],
 ['vitamina b15', 'pangamico'],
 ['vitamina b17', 'amigdalina'],
 ['vitamina b22', 'ratanhia'],
 ['vitamina n', 'pantotenico'],
 ['vitamina w'],
 ['vitamina f', 'graxos essenciais'],
 ['vitamina g', 'monofosfato de nicotinamida'],
 ['vitamina h', 'biotina'],
 ['vitamina l', 'adipico'],
 ['vitamina q', 'coenzima q10'],
 ['vitamina r', 'flavina'],
 ['vitamina s', 'aminobenzoico']
]

WORD_LIST = {
    "suplemento": WORD_LIST_SUPLEMENTO,
}