
def get_synonyms(word_list):
    return [sublist for sublist in word_list if len(sublist) > 1]

BLACK_LIST = [
    'regata',
    'camiseta',
    'coqueteleira',
    'mochila',
    'garraf',
    'bone',
    'marmita',
    'marmiteira',
    'galao',
    'baby look',
    'mascara',
    'porta capsulas',
    'shoulder bag',
    'frisbee',
    'bottle',
    'shorts',
    'jaqueta',
    'calça',
    'legging',
    'blusa',
    'top dux',
    'viseira',
    'bermuda',
    'necessaire',
    'bolsa',
    'moletom'
]

WORD_LIST_SUPLEMENTO = [['whey'],
 ['protein', 'proteina', 'proteica'],
 ['fibras'],
 ['beta alanina', 'betaalanina', 'alanina'],
 ['hair', 'cabelo'],
 ['nail', 'unha'],
 ['antioxidantes'],
 ['concentrado'],
 ['iso', 'isolado', 'isolate'],
 ['hidrolisado'],
 ['albumina'],
 ['barrinha', 'barra', 'bar'],
 ['colageno', 'colagen'],
 ['chocolate'],
 ['wafer', 'bolacha', 'biscoito'],
 ['blend', 'mistura'],
 ['veg', 'vegan', 'vegano', 'vegie', 'vegana'],
 ['rice', 'arroz'],
 ['ervilha', 'pea'],
 ['crisp'],
 ['soy', 'soja'],
 ['nuts'],
 ['alfajor'],
 ['egg', 'ovo'],
 ['caseinato'],
 ['calcio'],
 ['verisol'],
 ['zinco'],
 ['creatina', 'creatine', 'creatin', 'creapure'],
 ['monohidratada'],
 ['glutamin', 'glutamine', 'glutamina', 'lglutamina'],
 ['arginin', 'arginine', 'arginina'],
 ['bcaa', 'bca'],
 ['hmb', 'hydroxymethylbutyrate'],
 ['carnitin', 'carnitina', 'lcarnitina'],
 ['aminoacido'],
 ['triptofano'],
 ['taurina'],
 ['maca peruana'],
 ['leucin', 'leucine', 'lleucine'],
 ['mass', 'hipercalorico'],
 ['malto', 'dextrina', 'maltodextrina'],
 ['frutose'],
 ['dextrose', 'maltodextrose'],
 ['waxy maize', 'amido de milho'],
 ['batata doce'],
 ['dribose'],
 ['curcuma', 'acafrao'],
 ['coco'],
 ['oleo'],
 ['zinco'],
 ['melatonina'],
 ['psyllium'],
 ['transresveratrol'],
 ['testofen'],
 ['cha'],
 ['astaxantina'],
 ['zeaxantina'],
 ['cafein', 'cafe', 'cafeina', 'coffe', 'caffe', 'coffee'],
 ['cafe verde'],
 ['termogenico'],
 ['pretreino', 'workout', 'pretrein', 'preworkout', 'pre workout'],
 ['biotina'],
 ['hialuronico'],
 ['optimsm'],
 ['palatinose'],
 ['levagen'],
 ['fosfatidilserina'],
 ['acetil', 'nacetil'],
 ['cistein', 'lcisteina'],
 ['linhaca'],
 ['primula'],
 ['borragem'],
 ['krill'],
 ['peixe', 'dha', 'omega 3'],
 ['laranja'],
 ['cromo'],
 ['resveratrol'],
 ['zinco'],
 ['betacaroteno'],
 ['cartamo'],
 ['quitosana'],
 ['propolis'],
 ['lecitina'],
 ['melatonina'],
 ['multivitaminico', 'polivitaminico'],
 ['zma'],
 ['magnesio'],
 ['coco'],
 ['chia'],
 ['cromo'],
 ['picolinato'],
 ['spirulina'],
 ['picolinato'],
 ['alho'],
 ['beauty', 'beleza'],
 ['skin', 'pele'],
 ['imune', 'imunidade'],
 ['uva'],
 ['semente'],
 ['antiox'],
 ['espirulina'],
 ['gengibre'],
 ['tempero'],
 ['xylitol'],
 ['vit', 'vitamina', 'vitamin'],
 ['pasta de amendoim'],
 ['cha verde'],
 ['coenzima q10', 'vitamina q10'],
 ['vitamina a'],
 ['complexo b', 'vitamina b'],
 ['vitamina b1', 'tiamina'],
 ['vitamina b2', 'riboflavina'],
 ['vitamina b3', 'niacina'],
 ['vitamina b5', 'pantotenico'],
 ['vitamina b6', 'piridoxina'],
 ['vitamina b7', 'biotina'],
 ['vitamina b9', 'folico'],
 ['vitamina b12', 'cobalamina'],
 ['vitamina c', 'ascorbico'],
 ['vitamina d', 'calciferol'],
 ['vitamina e', 'tocoferol'],
 ['vitamina k', 'filoquinona'],
 ['vitamina k1', 'fitoquinona'],
 ['vitamina k2', 'menaquinona'],
 ['vitamina k7', 'mk7'],
 ['vitamina j', 'lipoico'],
 ['vitamina l1'],
 ['vitamina l2'],
 ['vitamina m'],
 ['vitamina o'],
 ['vitamina p', 'bioflavonoides'],
 ['vitamina t', 'bioflavonoides'],
 ['vitamina b4', 'adenina'],
 ['vitamina b8', 'inositol'],
 ['vitamina b10', 'paraaminobenzoico'],
 ['vitamina b11', 'salicilico'],
 ['vitamina b13', 'orotico'],
 ['vitamina b15', 'pangamico'],
 ['vitamina b17', 'amigdalina'],
 ['vitamina b22', 'ratanhia'],
 ['vitamina n', 'pantotenico'],
 ['vitamina w'],
 ['vitamina f', 'graxos essenciais'],
 ['vitamina g', 'monofosfato de nicotinamida'],
 ['vitamina h', 'biotina'],
 ['vitamina l', 'adipico'],
 ['vitamina q', 'coenzima q10'],
 ['vitamina r', 'flavina'],
 ['vitamina s', 'aminobenzoico']
]

WORD_LIST = {
    "supplement": WORD_LIST_SUPLEMENTO,
}

pronomes_pessoais = ['Eu', 'Tu', 'Ele', 'Ela', 'Nós', 'Vós', 'Eles', 'Elas', 'Mim', 'Ti', 'Si', 'Consigo']
pronomes_obliquos = ['Me', 'Te', 'Se', 'Nos', 'Vos', 'O', 'A', 'Lhe', 'Os', 'As', 'Nos', 'Vos', 'Se', 'Convosco', 'Lhes', 'Contigo']
pronomes_demonstrativos = ['Este', 'Esse', 'Aquele', 'Esta', 'Essa', 'Aquela', 'Isto', 'Isso', 'Aquilo', 'Estes', 'Esses', 'Aqueles', 'Estas', 'Essas', 'Aquelas', 'Iste']
pronomes_possessivos = ['Meu', 'Teu', 'Seu', 'Nosso', 'Vosso', 'Seu', 'Minha', 'Tua', 'Sua', 'Nossa', 'Vossa', 'Sua', 'Meus', 'Teus', 'Seus', 'Nossos', 'Vossos', 'Minhas', 'Tuas', 'Suas', 'Nossas', 'Vossas']
pronomes_indefinidos = ['Alguém', 'Ninguém', 'Todo', 'Algum', 'Nenhum', 'Outro', 'Muito', 'Pouco', 'Tanto', 'Cada', 'Algo', 'Tudo', 'Nada', 'Cada um', 'Qualquer', 'Poucos', 'Muitos', 'Vários', 'Outrem']
pronomes_relativos = ['Que', 'Qual', 'Quem', 'Onde', 'Cujo', 'O qual', 'Cuja', 'Quanto']
pronomes_interrogativos = ['Quem', 'O que', 'Qual', 'Quanto', 'Onde', 'Quando', 'Como', 'Por que', 'Qualquer coisa', 'Quanto a']
preposicoes = ['A', 'Ante', 'Até', 'Após', 'Com', 'Contra', 'De', 'Desde', 'Em', 'Entre', 'Para', 'Por', 'Perante', 'Sem', 'Sob', 'Sobre', 'Trás', 'Conforme', 'Contudo', 'Durante', 'Exceto', 'Mediant', 'Menos', 'Salvo', 'Segundo', 'Visto']

BRAZIL_PRONOUNS = pronomes_pessoais + pronomes_obliquos + pronomes_demonstrativos + pronomes_possessivos + pronomes_indefinidos + pronomes_relativos + pronomes_interrogativos + preposicoes

PRONOUNS = {
    "brazil": BRAZIL_PRONOUNS
}