from src.lib.wordlist.wordlist_flavor import WORDLIST_FLAVOR

KEYS_WORDLIST_FLAVOR = WORDLIST_FLAVOR.keys()

COLLECTIONS = {
    'whey': {
        "product": [
            "whey",
        ],
        "features": [
            "hidrolisad",
            "concentrad",
            "iso",
        ],
        "ingredients": [
            "colageno",
        ],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "sache",
            "barrinha",
            "crisp",
            "crunch",
            "alfajor",
            "display",
            "carboidratos",
            "mass",
            "dose",
            "manteiga de amendoim",
            "wafer",
            "drink",
            "shake",
            "cranberry",
        ],
        "maybe_not": [
            "manteiga de amendoim",
        ],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Whey Promoção",
        "indices_flavor": {
            "Whey Sabor": {
                "product": "whey",
                "flavor": None
            },
        },
        "indices": {
            "Whey": {
                "product": "whey",
            },
            "Whey Concentrado": {
                "product": "whey",
                "features": "concentrad",
            },
            "Whey Hidrolisado": {
                "product": "whey",
                "features": "hidrolisad",
            },
            "Whey Isolado": {
                "product": "whey",
                "features": "iso",
            },
        }
    },
    'whey_sache': {
        "product": [
            "whey",
        ],
        "features": [
            "hidrolisad",
            "concentrad",
            "iso",
            "veg",
            "sache",
        ],
        "ingredients": [
            "colageno",
        ],
        "flavor": {},
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "carboidratos",
            "crunch",
            "manteiga de amendoim",
            "crisp",
            "alfajor",
            "mass",
            "cranberry",
            "wafer",
            "drink",
        ],
        "maybe_not": [
            "manteiga de amendoim",
        ],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Whey Promoção",
        "indices_flavor": {
            "Whey Sabor": {
                "product": "whey",
                "flavor": None
            },
        },
        "indices": {
            "Whey Sache": {
                "product": "whey",
                "features": "sache",
            },
        }
    },
    'whey_kit': {
        "product": [
            "whey",
        ],
        "features": [
            "hidrolisad",
            "concentrad",
            "iso",
            "veg",
            "kit",
        ],
        "ingredients": [
            "colageno",
        ],
        "flavor": {},
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "sache",
            "crisp",
            "barrinha",
            "crunch",
            "cranberry",
            "carboidratos",
            "alfajor",
            "manteiga de amendoim",
            "mass",
            "dose",
            "wafer",
            "drink",
        ],
        "maybe_not": [
            "manteiga de amendoim",
        ],
        "default_collection": ["Proteínas"],
        "promotion_collection": None,
        "indices_flavor": {
            "Whey Sabor": {
                "product": "whey",
                "flavor": None
            },
        },
        "indices": {
            "Whey Kit": {
                "product": "whey",
                "features": "kit",
            },
        }
    },
    'whey_drink': {
        "product": [
            "whey",
            "drink",
        ],
        "features": [
            "drink",
            "hidrolisad",
            "concentrad",
            "iso",
            "veg",
        ],
        "ingredients": [],
        "flavor": {},
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "crisp",
            "kit",
            "sache",
            "barrinha",
            "carboidratos",
            "manteiga de amendoim",
            "crunch",
            "alfajor",
            "cranberry",
            "wafer",
        ],
        "maybe_not": [
            "manteiga de amendoim",
        ],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Whey Promoção",
        "indices_flavor": {
            "Whey Sabor": {
                "product": "whey",
                "flavor": None
            },
        },
        "indices": {
            "Whey Bebidas": {
                "product": "drink",
                "features": "whey"
            },
        }
    },
    'barrinha': {
        "product": [
            "barrinha",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [
            "colageno",
        ],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "alfajor",
            "capsula",
            "comprimido",
            "sache",
            "manteiga de amendoim",
            "wafer",
            "barbecue",
            "drink",
        ],
        "maybe_not": [],
        "promotion_collection": "Barrinhas Promoção",
        "indices_flavor": {
            "Barrinha Sabor": {
                "product": "barrinha",
                "flavor": None
            },
        },
        "indices": {
            "Barrinha": {
                "product": "barrinha"
            },
            "Barrinhas Veganas": {
                "product": "barrinha",
                "features": "veg",
            },
        }
    },
    'candy': {
        "product": [
            "crunch",
        ],
        "features": [
            "wafer",
            "alfajor",
        ],
        "ingredients": [
            "colageno",
        ],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "alfajor",
            "sache",
            "barbecue",
            "drink",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": {
            "Doces Sabor": {
                "product": "crunch",
                "flavor": None
            },
        },
        "indices": {
            "Doces": {
                "product": "crunch"
            },
            "Doces": {
                "features": "wafer"
            },
            "Doces": {
                "features": "alfajor"
            },
        }
    },
    'creatina': {
        "product": [
            "creatina",
        ],
        "features": [
            "veg",
            "creapure",
        ],
        "ingredients": [
        ],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "hidrolisad",
            "concentrad",
            "iso",
            "pretreino",
            "glutamina",
            "carnitin",
            "beef",
            "soy",
            "ervilha",
            "mass",
            "alfajor",
            "wafer",
            "drink",
        ],
        "maybe_not": [],
        "rule_fields": [
            {
                "field": "quantity",
                "name": "1kg",
                "range": [999, 10000],
            },
            {
                "field": "quantity",
                "name": "500g",
                "range": [499, 999],
            },
        ],
        "promotion_collection": "Creatina Promoção",
        "indices_flavor": [],
        "indices": {
            "Creatina": {
                "product": "creatina"
            },
            "Creatina Vegana": {
                "product": "creatina",
                "features": "veg",
            },
            "Creatina Creapure": {
                "product": "creatina",
                "features": "creapure",
            },
        }
    },
    'creatina_kit': {
        "product": [
            "creatina",
        ],
        "features": [
            "veg",
            "creapure",
            "kit"
        ],
        "ingredients": [
        ],
        "flavor": {},
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "whey",
            "barrinha",
            "pretreino",
            "beef",
            "soy",
            "ervilha",
            "mass",
            "alfajor",
            "wafer",
            "drink",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Creatina Kit": {
                "product": "creatina",
                "features": "kit",
            },
        }
    },
    'pretreino': {
        "product": [
            "pretreino",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [
            "cafeina",
            "betaalanina",
            "arginin",
        ],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "promotion_collection": "Pré-treino Promoção",
        "indices_flavor": [],
        "indices": {
            "Pré-treino": {
                "product": "pretreino"
            },
            "Pré-treino Vegano": {
                "product": "pretreino",
                "features": "veg",
            },
        }
    },
    'soy': {
        "product": [
            "soy",
            "protein",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "sache",
            'snack',
            "alfajor",
            "pretreino",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Proteína da Soja": {
                "product": "soy"
            },
        }
    },
    'ervilha': {
        "product": [
            "ervilha",
            "protein",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "sache",
            'snack',
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Proteína da Ervilha": {
                "product": "ervilha"
            },
        }
    },
    'rice': {
        "product": [
            "rice",
            "protein",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "sache",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Proteína do Arroz": {
                "product": "rice"
            },
        }
    },
    'protein': {
        "product": [
            "protein",
        ],
        "features": [
            "veg",
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "soy",
            "ervilha",
            "rice",
            "barrinha",
            "sache",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": [],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Proteínas": {
                "product": "protein"
            },
        }
    },
    'colageno': {
        "product": [
            "colageno",
        ],
        "features": [
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "alfajor",
            "beef",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Colageno": {
                "product": "colageno"
            },
        }
    },
    'casein': {
        "product": [
            "casein",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Caseina": {
                "product": "casein"
            },
        }
    },
    'albumina': {
        "product": [
            "albumina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Albumina": {
                "product": "albumina"
            },
        }
    },
    'beef': {
        "product": [
            "beef",
            "protein"
        ],
        "features": [
            "beef"
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "whey",
            "barrinha",
            "mass",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Proteína da Carne": {
                "product": "protein",
                "features": "beef"
            },
        }
    },
    'blend': {
        "product": [
            "blend",
            "protein"
        ],
        "features": [
            "blend"
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "mass",
            "leucin",
            "sache",
            "alfajor",
            "taurina",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Proteínas"],
        "promotion_collection": "Proteínas Promoção",
        "indices_flavor": [],
        "indices": {
            "Blend de Proteínas": {
                "product": "protein",
                "features": "blend"
            },
        }
    },
    'mass': {
        "product": [
            "mass",
        ],
        "features": [
            "protein"
        ],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Hipercalórico": {
                "product": "mass",
            },
        }
    },
    'manteiga_de_amendoim': {
        "product": [
            "manteiga de amendoim",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "alfajor",
            "wafer",
            "pretreino",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Pasta de Amendoim": {
                "product": "manteiga de amendoim",
            },
        }
    },
    'postreino': {
        "product": [
            "postreino",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "alfajor",
            "wafer",
            "pretreino",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Pós-treino": {
                "product": "postreino",
            },
        }
    },
    'intratreino': {
        "product": [
            "intratreino",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "alfajor",
            "wafer",
            "pretreino",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Intra-treino": {
                "product": "intratreino",
            },
        }
    },
    'waxymaize': {
        "product": [
            "waxymaize",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "nac",
            "kit",
            "barrinha",
            "creatina",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Carboidratos"],
        "promotion_collection": "Carboidratos Promoção",
        "indices_flavor": [],
        "indices": {
            "Waxy Maize": {
                "product": "waxymaize",
            },
        }
    },
    'maltodextrina': {
        "product": [
            "maltodextrina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Carboidratos"],
        "promotion_collection": "Carboidratos Promoção",
        "indices_flavor": [],
        "indices": {
            "Maltodextrina": {
                "product": "maltodextrina",
            },
        }
    },
    'dextrose': {
        "product": [
            "dextrose",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Carboidratos"],
        "promotion_collection": "Carboidratos Promoção",
        "indices_flavor": [],
        "indices": {
            "Dextrose": {
                "product": "dextrose",
            },
        }
    },
    'palatinose': {
        "product": [
            "palatinose",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Carboidratos"],
        "promotion_collection": "Carboidratos Promoção",
        "indices_flavor": [],
        "indices": {
            "Palatinose": {
                "product": "palatinose",
            },
        }
    },
    'bcaa': {
        "product": [
            "bcaa",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "betaalanina",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "pretreino",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Aminoacidos"],
        "promotion_collection": "Aminoacidos Promoção",
        "indices_flavor": [],
        "indices": {
            "BCAA": {
                "product": "bcaa",
            },
        }
    },
    'arginin': {
        "product": [
            "arginin",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "betaalanina",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "pretreino",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Aminoacidos"],
        "promotion_collection": "Aminoacidos Promoção",
        "indices_flavor": [],
        "indices": {
            "Arginina": {
                "product": "arginin",
            },
        }
    },
    'glutamin': {
        "product": [
            "glutamin",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "arginin",
            "betaalanina",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "pretreino",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Aminoacidos"],
        "promotion_collection": "Aminoacidos Promoção",
        "indices_flavor": [],
        "indices": {
            "Glutamina": {
                "product": "glutamin",
            },
        }
    },
    'betaalanina': {
        "product": [
            "betaalanina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Aminoacidos"],
        "promotion_collection": "Aminoacidos Promoção",
        "indices_flavor": [],
        "indices": {
            "Beta-alanina": {
                "product": "betaalanina",
            },
        }
    },
    'taurina': {
        "product": [
            "taurina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "cafeina",
            "creatina",
            "vitamina b",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Aminoacidos"],
        "promotion_collection": "Aminoacidos Promoção",
        "indices_flavor": [],
        "indices": {
            "Taurina": {
                "product": "taurina",
            },
        }
    },
    'multivitaminico': {
        "product": [
            "multivitaminico",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Multivitaminico": {
                "product": "multivitaminico",
            },
        }
    },
    'vitamina_a': {
        "product": [
            "vitamina a",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "omega 3",
            "oleo",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina A": {
                "product": "vitamina a",
            },
        }
    },
    'vitamina_b': {
        "product": [
            "vitamina b",
        ],
        "features": [],
        "ingredients": [
            "vitamina b10",
            "vitamina b11",
            "vitamina b12",
            "vitamina b13",
            "vitamina b15",
            "vitamina b17",
            "vitamina b2",
            "vitamina b22",
            "vitamina b3",
            "vitamina b4",
            "vitamina b5",
            "vitamina b6",
            "vitamina b8",
            "vitamina b9",
        ],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina B": {
                "product": "vitamina b",
            },
        }
    },
    'biotina': {
        "product": [
            "biotina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Biotina": {
                "product": "biotina",
            },
        }
    },
    'vitamina_c': {
        "product": [
            "vitamina c",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina C": {
                "product": "vitamina c",
            },
        }
    },
    'vitamina_d': {
        "product": [
            "vitamina d",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina D": {
                "product": "vitamina d",
            },
        }
    },
    'vitamina_e': {
        "product": [
            "vitamina e",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina E": {
                "product": "vitamina e",
            },
        }
    },
    'vitamina_k': {
        "product": [
            "vitamina k",
        ],
        "features": [],
        "ingredients": [
            "vitamina k1",
            "vitamina k2",
            "vitamina k7",
        ],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Vitamina K": {
                "product": "vitamina k",
            },
        }
    },
    'vitamina_q': {
        "product": [
            "vitamina q",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Coenzima Q10": {
                "product": "vitamina q",
            },
        }
    },
    'zinco': {
        "product": [
            "zinco",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Zinco": {
                "product": "zinco",
            },
        }
    },
    'calcio': {
        "product": [
            "calcio",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Cálcio": {
                "product": "calcio",
            },
        }
    },
    'magnesio': {
        "product": [
            "magnesio",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Magnésio": {
                "product": "magnesio",
            },
        }
    },
    'ferro': {
        "product": [
            "ferro",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Vitaminas e Minerais"],
        "promotion_collection": "Vitaminas e Minerais Promoção",
        "indices_flavor": [],
        "indices": {
            "Ferro": {
                "product": "ferro",
            },
        }
    },
    'termogenico': {
        "product": [
            "termogenico",
        ],
        "features": [],
        "ingredients": [],
        "score_per_ingredients": True,
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Termogenicos": {
                "product": "termogenico",
            },
        }
    },
    'cafeina': {
        "product": [
            "cafeina",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Cafeina": {
                "product": "cafeina",
            },
        }
    },
    'chaverde': {
        "product": [
            "chaverde",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "blend",
            "pretreino",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Chá-verde": {
                "product": "chaverde",
            },
        }
    },
    'guarana': {
        "product": [
            "guarana",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "bcaa",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Guaraná": {
                "product": "guarana",
            },
        }
    },
    'gengibre': {
        "product": [
            "gengibre",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Gengibre": {
                "product": "gengibre",
            },
        }
    },
    'carnitin': {
        "product": [
            "carnitin",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Termogenicos"],
        "promotion_collection": "Termogenicos Promoção",
        "indices_flavor": [],
        "indices": {
            "Carnitina": {
                "product": "carnitin",
            },
        }
    },
    'omega_3': {
        "product": [
            "omega 3",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "sache",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Oleos"],
        "promotion_collection": "Oleos Promoção",
        "indices_flavor": [],
        "indices": {
            "ômega 3": {
                "product": "omega 3",
            },
        }
    },
    'oleo_de_coco': {
        "product": [
            "oleo de coco",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Oleos"],
        "promotion_collection": "Oleos Promoção",
        "indices_flavor": [],
        "indices": {
            "Óleo de Coco": {
                "product": "oleo de coco",
            },
        }
    },
    'oleo_de_cartamo': {
        "product": [
            "oleo de cartamo",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Oleos"],
        "promotion_collection": "Oleos Promoção",
        "indices_flavor": [],
        "indices": {
            "Óleo de cartamo": {
                "product": "oleo de cartamo",
            },
        }
    },
    'krill': {
        "product": [
            "krill",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "omega 3",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "default_collection": ["Oleos"],
        "promotion_collection": "Oleos Promoção",
        "indices_flavor": [],
        "indices": {
            "Óleo de Krill": {
                "product": "krill",
            },
        }
    },
    'curcuma': {
        "product": [
            "curcuma",
        ],
        "features": [],
        "ingredients": [],
        "flavor": KEYS_WORDLIST_FLAVOR,
        "format": [],
        "is_not": [
            "endurance",
            "granola",
            "melatonina",
            "kit",
            "barrinha",
            "creatina",
            "glutamin",
            "bcaa",
            "pretreino",
            "blend",
            "ervilha",
            "beef",
            "omega 3",
            "iso",
            "barbecue",
            "soy",
            "mass",
            "whey",
            "alfajor",
            "wafer",
        ],
        "maybe_not": [],
        "promotion_collection": None,
        "indices_flavor": [],
        "indices": {
            "Curcuma": {
                "product": "curcuma",
            },
        }
    },
}
