from src.lib.wordlist.wordlist_flavor import WORDLIST_FLAVOR
from src.lib.wordlist.wordlist_format import WORDLIST_FORMAT

BLACK_LIST = [
    "regata",
    "camiseta",
    "coqueteleira",
    "mochila",
    "garraf",
    "bone",
    "marmita",
    "marmiteira",
    "galao",
    "baby look",
    "mascara",
    "porta capsulas",
    "shoulder bag",
    "frisbee",
    "bottle",
    "shorts",
    "jaqueta",
    "calça",
    "legging",
    "blusa",
    "top dux",
    "viseira",
    "bermuda",
    "necessaire",
    "bolsa",
    "moletom",
    "tank top",
    "t-shirt",
    "shaker",
    "backpack",
    "bottle",
    "cap",
    "lunchbox",
    "cooler bag",
    "jug",
    "baby tee",
    "mask",
    "pill organizer",
    "shoulder bag",
    "frisbee",
    "bottle",
    "shorts",
    "jacket",
    "pants",
    "leggings",
    "sweater",
    "dux top",
    "visor",
    "bermuda shorts",
    "pouch",
    "bag",
    "sweatshirt",
]

SUPPLEMENT_COMPONENT_LIST = {
    "nac": {
        "synonyms": [
            "nac",
            "acetil",
            "nacetil",
            "n acetil",
            "cisteina",
            "l cisteina",
            "lcisteina",
        ],
        "exact_term": True,
        "brazil": "NAC",
        "united_states": "NAC",
    },
    "albumina": {
        "synonyms": [
            "albumin",
            "albumina",
            "albumin",
            "albumi",
        ],
        "exact_term": False,
        "brazil": "albumina",
        "united_states": "albumin",
    },
    "alho": {
        "synonyms": [
            "garlic",
            "alho",
        ],
        "exact_term": False,
        "brazil": "alho",
        "united_states": "garlic",
    },
    "aminoacido": {
        "synonyms": [
            "amino acid",
            "aminoacido",
        ],
        "exact_term": False,
        "brazil": "aminoácido",
        "united_states": "amino acid",
    },
    "antioxidante": {
        "synonyms": [
            "antioxidant",
            "antioxidante",
            "antiox",
        ],
        "exact_term": False,
        "brazil": "antioxidante",
        "united_states": "antioxidant",
    },
    "arginin": {
        "synonyms": [
            "arginine",
            "argin",
            "arginin",
            "arginine",
            "l arginine",
            "larginine",
            "arginina",
            "larginina",
            "l arginina",
        ],
        "exact_term": False,
        "brazil": "arginina",
        "united_states": "arginine",
    },
    "astaxantina": {
        "synonyms": [
            "astaxanthin",
            "astaxantina",
        ],
        "exact_term": False,
        "brazil": "astaxantina",
        "united_states": "astaxanthin",
    },
    "batata doce": {
        "synonyms": [
            "sweet potato",
            "batata doce",
        ],
        "exact_term": False,
        "brazil": "batata doce",
        "united_states": "sweet potato",
    },
    "bcaa": {
        "synonyms": [
            "bcaa",
            "bca",
        ],
        "exact_term": False,
        "brazil": "BCAA",
        "united_states": "BCAA",
    },
    "beauty": {
        "synonyms": [
            "beauty",
            "beauty",
            "beleza",
        ],
        "exact_term": False,
        "brazil": "beleza",
        "united_states": "beauty",
    },
    "beef": {
        "synonyms": [
            "beef",
            "carn",
            "carne",
            "bovina",
        ],
        "exact_term": True,
        "brazil": "carne",
        "united_states": "beef",
    },
    "betaalanina": {
        "synonyms": [
            "beta-alanine",
            "beta alanina",
            "betaalanina",
            "alanina",
            "alanine",
        ],
        "exact_term": False,
        "brazil": "beta-alanina",
        "united_states": "beta-alanine",
    },
    "betacaroteno": {
        "synonyms": [
            "beta-carotene",
            "betacaroteno",
        ],
        "exact_term": False,
        "brazil": "beta-carotene",
        "united_states": "beta-carotene",
    },
    "borragem": {
        "synonyms": [
            "borage",
            "borragem",
        ],
        "exact_term": False,
        "brazil": "borragem",
        "united_states": "borage",
    },
    "termogenico": {
        "synonyms": [
            "thermogenic",
            "termo",
            "termogenico",
            "termogênico",
            "termogenicos",
            "termogênicos",
        ],
        "exact_term": False,
        "brazil": "termogênico",
        "united_states": "thermogenic",
    },
    "tcm": {
        "synonyms": [
            "mct",
            "tcm",
        ],
        "exact_term": False,
        "brazil": "TCM",
        "united_states": "MCT",
    },
    "calcio": {
        "synonyms": [
            "calcium",
            "calcio",
        ],
        "exact_term": False,
        "brazil": "cálcio",
        "united_states": "calcium",
    },
    "carboidrato": {
        "synonyms": [
            "carbohydrate",
            "carboidrato",
            "carbohidrato",
            "carbohydrate",
            "kohlenhydrat",
            "carboidrati",
            "carbo",
            "karbohydrat",
            "glucide",
            "carbohydrates",
            "carbs",
            "carb",
        ],
        "exact_term": False,
        "brazil": "carboidrato",
        "united_states": "carbohydrate",
    },
    "carnitin": {
        "synonyms": [
            "carnitine",
            "carnitin",
            "carnitina",
            "lcarnitina",
            "l carnitina",
            "l carn",
        ],
        "exact_term": False,
        "brazil": "carnitina",
        "united_states": "carnitine",
    },
    "cartamo": {
        "synonyms": [
            "safflower",
            "cartamo",
        ],
        "exact_term": False,
        "brazil": "cártamo",
        "united_states": "safflower",
    },
    "oleo de cartamo": {
        "synonyms": [
            "safflower oil",
            "oleo de cartamo",
        ],
        "exact_term": False,
        "brazil": "óleo de cartamo",
        "united_states": "safflower oil",
    },
    "casein": {
        "synonyms": [
            "casein",
            "caseinato",
            "caseina",
            "casein",
        ],
        "exact_term": False,
        "brazil": "caseina",
        "united_states": "casein",
    },
    "cha": {
        "synonyms": [
            "tea",
            "cha",
        ],
        "exact_term": False,
        "brazil": "chá",
        "united_states": "tea",
    },
    "guarana": {
        "synonyms": [
            "guarana",
            "guarana",
        ],
        "exact_term": False,
        "brazil": "guaraná",
        "united_states": "guarana",
    },
    "chaverde": {
        "synonyms": [
            "green tea",
            "chaverde",
            "cha verde",
        ],
        "exact_term": False,
        "brazil": "chá verde",
        "united_states": "green tea",
    },
    "chia": {
        "synonyms": [
            "chia",
            "chia",
        ],
        "exact_term": False,
        "brazil": "chia",
        "united_states": "chia",
    },
    "cistein": {
        "synonyms": [
            "cysteine",
            "cistein",
            "lcisteina",
        ],
        "exact_term": False,
        "brazil": "cisteína",
        "united_states": "cysteine",
    },
    "colageno": {
        "synonyms": [
            "collagen",
            "colageno",
            "colagen",
            "collagen",
        ],
        "exact_term": False,
        "brazil": "colágeno",
        "united_states": "collagen",
    },
    "vitamina b": {
        "synonyms": [
            "vitamin b complex",
            "complexo b",
            "vitamina b",
        ],
        "exact_term": False,
        "brazil": "vitamina B",
        "united_states": "vitamin B complex",
    },
    "concentrad": {
        "synonyms": [
            "concentrate",
            "wpc",
            "concentrad",
            "concentrado",
        ],
        "exact_term": True,
        "brazil": "concentrado",
        "united_states": "concentrate",
    },
    "creatina": {
        "synonyms": [
            "creatine",
            "creatina",
            "creatine",
            "creatin",
        ],
        "exact_term": False,
        "brazil": "creatina",
        "united_states": "creatine",
    },
    "crisp": {
        "synonyms": [
            "crisp",
            "crisp",
        ],
        "exact_term": False,
        "brazil": "crisp",
        "united_states": "crisp",
    },
    "cromo": {
        "synonyms": [
            "chromium",
            "cromo",
            "cromo",
        ],
        "exact_term": False,
        "brazil": "cromo",
        "united_states": "chromium",
    },
    "cafeina": {
        "synonyms": [
            "caffeine",
            "cafeína",
            "caffeine",
            "cafeina",
            "suplemento de cafeína",
        ],
        "exact_term": False,
        "brazil": "cafeína",
        "united_states": "caffeine",
    },
    "curcuma": {
        "synonyms": [
            "turmeric",
            "curcuma",
            "acafrao",
        ],
        "exact_term": False,
        "brazil": "cúrcuma",
        "united_states": "turmeric",
    },
    "dextrose": {
        "synonyms": [
            "dextrose",
            "dextrose",
            "dextros",
            "maltodextrose",
            "maltodextros",
            "malto dextrose",
        ],
        "exact_term": False,
        "brazil": "dextrose",
        "united_states": "dextrose",
    },
    "dribose": {
        "synonyms": [
            "d-ribose",
            "dribose",
            "d ribose",
            "ribose",
            "dribose",
        ],
        "exact_term": False,
        "brazil": "ribose",
        "united_states": "D-ribose",
    },

    "ervilha": {
        "synonyms": [
            "pea",
            "ervilha",
            "pea",
        ],
        "exact_term": False,
        "brazil": "ervilha",
        "united_states": "pea",
    },
    "espirulina": {
        "synonyms": [
            "spirulina",
            "espirulina",
        ],
        "exact_term": False,
        "brazil": "espirulina",
        "united_states": "spirulina",
    },
    "fibra": {
        "synonyms": [
            "fiber",
            "fibra",
        ],
        "exact_term": False,
        "brazil": "fibra",
        "united_states": "fiber",
    },
    "fosfatidilserina": {
        "synonyms": [
            "phosphatidylserine",
            "fosfatidilserina",
        ],
        "exact_term": False,
        "brazil": "fosfatidilserina",
        "united_states": "phosphatidylserine",
    },
    "frutose": {
        "synonyms": [
            "fructose",
            "frutose",
        ],
        "exact_term": False,
        "brazil": "frutose",
        "united_states": "fructose",
    },
    "gengibre": {
        "synonyms": [
            "ginger",
            "gengibre",
        ],
        "exact_term": False,
        "brazil": "gengibre",
        "united_states": "ginger",
    },
    "gergelim": {
        "synonyms": [
            "sesame",
            "gergelim",
        ],
        "exact_term": False,
        "brazil": "gergelim",
        "united_states": "sesame",
    },
    "glutamin": {
        "synonyms": [
            "glutamine",
            "glutamin",
            "glutamine",
            "glutamina",
            "lglutamina",
            "gluta",
        ],
        "exact_term": False,
        "brazil": "glutamina",
        "united_states": "glutamine",
    },
    "hair": {
        "synonyms": [
            "hair",
            "hair",
            "cabelo",
        ],
        "exact_term": False,
        "brazil": "cabelo",
        "united_states": "hair",
    },
    "hialuronico": {
        "synonyms": [
            "hyaluronic acid",
            "hialuronico",
        ],
        "exact_term": False,
        "brazil": "hialurônico",
        "united_states": "hyaluronic acid",
    },
    "hidrolisad": {
        "synonyms": [
            "hydrolyzed",
            "hidrolisad",
            "hidrolisado",
            "hydro",
            "wph",
        ],
        "exact_term": True,
        "brazil": "hidrolisado",
        "united_states": "hydrolyzed",
    },
    "churros": {
        "synonyms": [
            "churros",
            "churros",
        ],
        "exact_term": False,
        "brazil": "churros",
        "united_states": "churros",
    },
    "hmb": {
        "synonyms": [
            "hmb",
            "hmb",
            "hydroxymethylbutyrate",
        ],
        "exact_term": False,
        "brazil": "HMB",
        "united_states": "HMB",
    },
    "imune": {
        "synonyms": [
            "immune",
            "imune",
            "imunidade",
        ],
        "exact_term": False,
        "brazil": "imunidade",
        "united_states": "immune",
    },
    "iso": {
        "synonyms": [
            "isolate",
            "iso",
            "wpi",
            "isolado",
            "isolate",
            "isolada",
        ],
        "exact_term": True,
        "brazil": "isolado",
        "united_states": "isolate",
    },
    "kit": {
        "synonyms": [
            "kit",
            "kit",
            "combo",
            "elite box",
        ],
        "exact_term": False,
        "brazil": "kit",
        "united_states": "kit",
    },
    "krill": {
        "synonyms": [
            "krill oil",
            "krill",
            "oleo de krill",
        ],
        "exact_term": False,
        "brazil": "óleo de krill",
        "united_states": "krill oil",
    },
    "lecitina": {
        "synonyms": [
            "lecithin",
            "lecitina",
        ],
        "exact_term": False,
        "brazil": "lecitina",
        "united_states": "lecithin",
    },
    "leucin": {
        "synonyms": [
            "leucine",
            "leucin",
            "leucine",
            "lleucine",
        ],
        "exact_term": False,
        "brazil": "leucina",
        "united_states": "leucine",
    },
    "levagen": {
        "synonyms": [
            "levagen",
            "levagen",
        ],
        "exact_term": False,
        "brazil": "levagen",
        "united_states": "Levagen",
    },
    "linhaca": {
        "synonyms": [
            "flaxseed",
            "linhaca",
        ],
        "exact_term": False,
        "brazil": "linhaça",
        "united_states": "flaxseed",
    },
    "maca peruana": {
        "synonyms": [
            "peruvian maca",
            "maca peruana",
        ],
        "exact_term": False,
        "brazil": "maca peruana",
        "united_states": "Peruvian maca",
    },
    "magnesio": {
        "synonyms": [
            "magnesium",
            "magnesio",
            "magnesi",
        ],
        "exact_term": False,
        "brazil": "magnésio",
        "united_states": "magnesium",
    },
    "ferro": {
        "synonyms": [
            "iron",
            "ferro",
            "iron",
            "iron supplement",
            "suplemento de ferro",
        ],
        "exact_term": False,
        "brazil": "ferro",
        "united_states": "iron",
    },
    "maltodextrina": {
        "synonyms": [
            "maltodextrin",
            "dextrina",
            "maltodextrina",
            "malto dextrina",
            "maltodextrin",
        ],
        "exact_term": False,
        "brazil": "maltodextrina",
        "united_states": "maltodextrin",
    },
    "mass": {
        "synonyms": [
            "mass gainer",
            "mass",
            "hipercalorico",
        ],
        "exact_term": True,
        "brazil": "Hipercalórico",
        "united_states": "mass gainer",
    },
    "melatonina": {
        "synonyms": [
            "melatonin",
            "melatonina",
            "melatonina",
        ],
        "exact_term": False,
        "brazil": "melatonina",
        "united_states": "melatonin",
    },
    "monohidratada": {
        "synonyms": [
            "monohydrate",
            "monohidratada",
        ],
        "exact_term": False,
        "brazil": "monohidratada",
        "united_states": "monohydrate",
    },
    "creapure": {
        "synonyms": [
            "creapure",
            "creapure",
        ],
        "exact_term": False,
        "brazil": "creapure",
        "united_states": "Creapure",
    },
    "multivitaminico": {
        "synonyms": [
            "multivitamin",
            "multivitaminico",
            "polivitaminico",
        ],
        "exact_term": False,
        "brazil": "multivitamínico",
        "united_states": "multivitamin",
    },
    "mineral": {
        "synonyms": [
            "mineral",
            "minerai",
            "mineral",
        ],
        "exact_term": False,
        "brazil": "mineral",
        "united_states": "mineral",
    },
    "nail": {
        "synonyms": [
            "nail",
            "nail",
            "unha",
        ],
        "exact_term": False,
        "brazil": "unha",
        "united_states": "nail",
    },
    "oleo": {
        "synonyms": [
            "oil",
            "oleo",
        ],
        "exact_term": False,
        "brazil": "óleo",
        "united_states": "oil",
    },
    "oleo de coco": {
        "synonyms": [
            "coconut oil",
            "oleo de coco",
        ],
        "exact_term": False,
        "brazil": "óleo de coco",
        "united_states": "coconut oil",
    },
    "ketchup": {
        "synonyms": [
            "ketchup",
            "ketchup",
        ],
        "exact_term": False,
        "brazil": "ketchup",
        "united_states": "ketchup",
    },
    "barbecue": {
        "synonyms": [
            "barbecue",
            "barbecue",
        ],
        "exact_term": False,
        "brazil": "barbecue",
        "united_states": "barbecue",
    },
    "mostarda": {
        "synonyms": [
            "mustard",
            "mostarda",
        ],
        "exact_term": False,
        "brazil": "mostarda",
        "united_states": "mustard",
    },
    "maionese": {
        "synonyms": [
            "mayonnaise",
            "maionese",
        ],
        "exact_term": False,
        "brazil": "maionese",
        "united_states": "mayonnaise",
    },
    "optimsm": {
        "synonyms": [
            "optimsm",
            "optimsm",
        ],
        "exact_term": False,
        "brazil": "optimsm",
        "united_states": "OptiMSM",
    },
    "palatinose": {
        "synonyms": [
            "palatinose",
            "palatinose",
            "isomaltulose",
        ],
        "exact_term": False,
        "brazil": "palatinose",
        "united_states": "palatinose",
    },
    "enzima": {
        "synonyms": [
            "enzyme",
            "enzima",
            "enzimas",
            "enzyme",
            "enzymes",
        ],
        "exact_term": False,
        "brazil": "enzima",
        "united_states": "enzyme",
    },
    "protease": {
        "synonyms": [
            "protease",
            "protease",
            "proteasa",
            "protease",
        ],
        "exact_term": False,
        "brazil": "protease",
        "united_states": "protease",
    },
    "propolis": {
        "synonyms": [
            "propolis",
            "propolis",
        ],
        "exact_term": False,
        "brazil": "própolis",
        "united_states": "propolis",
    },
    "lactase": {
        "synonyms": [
            "lactase",
            "lactase",
            "lactasa",
            "lactase",
        ],
        "exact_term": False,
        "brazil": "lactase",
        "united_states": "lactase",
    },
    "lipase": {
        "synonyms": [
            "lipase",
            "lipase",
            "lipasa",
            "lipase",
        ],
        "exact_term": False,
        "brazil": "lipase",
        "united_states": "lipase",
    },
    "bromelina": {
        "synonyms": [
            "bromelain",
            "bromelina",
            "bromelain",
            "bromelina",
        ],
        "exact_term": False,
        "brazil": "bromelina",
        "united_states": "bromelain",
    },
    "crisp": {
        "synonyms": [
            "crisp",
            "crisp",
            "crocante",
            "sabor crisp",
            "crisp flavor",
        ],
        "exact_term": False,
        "brazil": "crisp",
        "united_states": "crisp",
    },
    "amilase": {
        "synonyms": [
            "amylase",
            "amilase",
            "amylase",
            "amilasa",
        ],
        "exact_term": False,
        "brazil": "amilase",
        "united_states": "amylase",
    },
    "manteiga de amendoim": {
        "synonyms": [
            "peanut butter",
            "pasta de amendoim",
            "manteiga de amendoim",
            "peanut butter",
            "peanutbutter",
            "peanut butter flavor",
        ],
        "exact_term": False,
        "brazil": "pasta de ,amendoim",
        "united_states": "peanut butter",
    },
    "snack": {
        "synonyms": [
            "snack",
            "snack",
            "lanche",
            "snack flavor",
            "sabor snack",
        ],
        "exact_term": False,
        "brazil": "snack",
        "united_states": "snack",
    },
    "amendoim": {
        "synonyms": [
            "peanut",
            "amendoim",
            "peanut",
            "almonds",
        ],
        "exact_term": False,
        "brazil": "amendoim",
        "united_states": "peanut",
    },
    "omega 3": {
        "synonyms": [
            "omega 3",
            "oleo de peixe",
            "dha",
            "epa",
            "omega 3",
            "omega",
        ],
        "exact_term": False,
        "brazil": "ômega 3",
        "united_states": "omega 3",
    },
    "omega 6": {
        "synonyms": [
            "omega 6",
            "omega 6",
            "linoléico",
        ],
        "exact_term": False,
        "brazil": "ômega 6",
        "united_states": "omega 6",
    },
    "picolinato": {
        "synonyms": [
            "picolinate",
            "picolinato",
            "picolinato",
        ],
        "exact_term": False,
        "brazil": "picolinato",
        "united_states": "picolinate",
    },
    "mct": {
        "synonyms": [
            "mct",
            "MCT",
            "óleo MCT",
            "oleo MCT",
            "MCT oil",
            "medium chain triglycerides",
            "triglicerídeos de cadeia média",
            "triglicerideos de cadeia media",
        ],
        "exact_term": False,
        "brazil": "MCT",
        "united_states": "MCT",
    },
    "pretreino": {
        "synonyms": [
            "pre-workout",
            "pretreino",
            "pre treino",
            "pre-treino",
            "pretrein",
            "pre trein",
            "preworkout",
            "pre workout",
            "pre-workout",
        ],
        "exact_term": False,
        "brazil": "pré-treino",
        "united_states": "pre-workout",
    },
    "endurance": {
        "synonyms": [
            "endurance",
            "endurance",
        ],
        "exact_term": False,
        "brazil": "endurance",
        "united_states": "endurance",
    },
    "postreino": {
        "synonyms": [
            "post-workout",
            "postreino",
            "pos treino",
            "pos-treino",
            "post workout",
            "post-workout",
            "postworkout",
        ],
        "exact_term": False,
        "brazil": "pós-trein,o",
        "united_states": "post-workout",
    },
    "intratreino": {
        "synonyms": [
            "intra-workout",
            "intra-treino",
            "intratreino",
            "intra treino",
            "intra workout",
            "intra-workout",
            "intraworkout",
        ],
        "exact_term": False,
        "brazil": "intra-tre,ino",
        "united_states": "intra-workout",
    },
    "primula": {
        "synonyms": [
            "evening primrose",
            "primula",
        ],
        "exact_term": False,
        "brazil": "prímula",
        "united_states": "evening primrose",
    },
    "propoli": {
        "synonyms": [
            "propolis",
            "propoli",
        ],
        "exact_term": False,
        "brazil": "própolis",
        "united_states": "propolis",
    },
    "dose": {
        "synonyms": [
            "dose",
            "dose",
            "dosage",
        ],
        "exact_term": False,
        "brazil": "dose",
        "united_states": "dose",
    },
    "protein": {
        "synonyms": [
            "protein",
            "protein",
            "proteina",
            "proteica",
        ],
        "exact_term": False,
        "brazil": "proteina",
        "united_states": "protein",
    },
    "psyllium": {
        "synonyms": [
            "psyllium",
            "psyllium",
        ],
        "exact_term": False,
        "brazil": "psílio",
        "united_states": "psyllium",
    },
    "quitosana": {
        "synonyms": [
            "chitosan",
            "quitosana",
        ],
        "exact_term": False,
        "brazil": "quitosana",
        "united_states": "chitosan",
    },
    "resveratrol": {
        "synonyms": [
            "resveratrol",
            "resveratrol",
        ],
        "exact_term": False,
        "brazil": "resveratrol",
        "united_states": "resveratrol",
    },
    "rice": {
        "synonyms": [
            "rice",
            "rice",
            "arroz",
        ],
        "exact_term": False,
        "brazil": "arroz",
        "united_states": "rice",
    },
    "semente": {
        "synonyms": [
            "seed",
            "semente",
        ],
        "exact_term": False,
        "brazil": "semente",
        "united_states": "seed",
    },
    "skin": {
        "synonyms": [
            "skin",
            "skin",
            "pele",
        ],
        "exact_term": False,
        "brazil": "pele",
        "united_states": "skin",
    },
    "soy": {
        "synonyms": [
            "soy",
            "soy",
            "soja",
        ],
        "exact_term": False,
        "brazil": "soja",
        "united_states": "soy",
    },
    "spirulina": {
        "synonyms": [
            "spirulina",
            "spirulina",
        ],
        "exact_term": False,
        "brazil": "spirulina",
        "united_states": "spirulina",
    },
    "taurina": {
        "synonyms": [
            "taurine",
            "taurina",
            "taurine",
            "taurin",
        ],
        "exact_term": False,
        "brazil": "taurina",
        "united_states": "taurine",
    },
    "tempero": {
        "synonyms": [
            "seasoning",
            "tempero",
        ],
        "exact_term": False,
        "brazil": "tempero",
        "united_states": "seasoning",
    },
    "testofen": {
        "synonyms": [
            "testofen",
            "testofen",
        ],
        "exact_term": False,
        "brazil": "testofen",
        "united_states": "Testofen",
    },
    "tyrosin": {
        "synonyms": [
            "tyrosine",
            "tyrosin",
            "tirosin",
            "tyrosine",
            "tirosina",
            "tirosine",
            "l tyrosine",
            "ltyrosine",
            "l tirosina",
            "l tirosine",
            "ltirosina",
            "ltirosine",
        ],
        "exact_term": False,
        "brazil": "tirosina",
        "united_states": "tyrosine",
    },
    "transresveratrol": {
        "synonyms": [
            "trans-resveratrol",
            "transresveratrol",
            "trans resveratrol",
        ],
        "exact_term": False,
        "brazil": "trans-resveratrol",
        "united_states": "trans-resveratrol",
    },
    "triptofano": {
        "synonyms": [
            "tryptophan",
            "triptofano",
        ],
        "exact_term": False,
        "brazil": "triptofano",
        "united_states": "tryptophan",
    },
    "leucina": {
        "synonyms": [
            "leucine",
            "leucina",
        ],
        "exact_term": False,
        "brazil": "leucina",
        "united_states": "leucine",
    },
    "valina": {
        "synonyms": [
            "valine",
            "valina",
        ],
        "exact_term": False,
        "brazil": "valina",
        "united_states": "valine",
    },
    "isoleucina": {
        "synonyms": [
            "isoleucine",
            "isoleucina",
        ],
        "exact_term": False,
        "brazil": "isoleucina",
        "united_states": "isoleucine",
    },
    "lisina": {
        "synonyms": [
            "lysine",
            "lisina",
        ],
        "exact_term": False,
        "brazil": "lisina",
        "united_states": "lysine",
    },
    "fenilalanina": {
        "synonyms": [
            "phenylalanine",
            "fenilalanina",
        ],
        "exact_term": False,
        "brazil": "fenilalanina",
        "united_states": "phenylalanine",
    },
    "treonina": {
        "synonyms": [
            "threonine",
            "treonina",
        ],
        "exact_term": False,
        "brazil": "treonina",
        "united_states": "threonine",
    },
    "metionina": {
        "synonyms": [
            "methionine",
            "metionina",
        ],
        "exact_term": False,
        "brazil": "metionina",
        "united_states": "methionine",
    },
    "silimarina": {
        "synonyms": [
            "silymarin",
            "silimarina",
        ],
        "exact_term": False,
        "brazil": "silimarina",
        "united_states": "silymarin",
    },
    "histidina": {
        "synonyms": [
            "histidine",
            "histidina",
            "lhistidina",
            "l histidina",
        ],
        "exact_term": False,
        "brazil": "histidina",
        "united_states": "histidine",
    },
    "veg": {
        "synonyms": [
            "vegan",
            "veg",
            "vegan",
            "vegano",
            "vegie",
            "vegana",
        ],
        "exact_term": True,
        "brazil": "vegano",
        "united_states": "vegan",
    },
    "vegetarian": {
        "synonyms": [
            "vegetarian",
            "vegetarian",
            "vegetariano",
            "vegetariana",
            "veggie",
            "vegetarianismo",
        ],
        "exact_term": False,
        "brazil": "vegetariano",
        "united_states": "vegetarian",
    },
    "verisol": {
        "synonyms": [
            "verisol",
            "verisol",
        ],
        "exact_term": False,
        "brazil": "verisol",
        "united_states": "Verisol",
    },
    "vitamina": {
        "synonyms": [
            "vitamin",
            "vitamina",
            "vitaminas",
            "vitamin",
        ],
        "exact_term": False,
        "brazil": "vitamina",
        "united_states": "vitamin",
    },
    "vitamina a": {
        "synonyms": [
            "vitamin a",
            "vitamina a",
            "retinol",
            "retinal",
            "retinoico",
        ],
        "exact_term": False,
        "brazil": "vitamina a",
        "united_states": "vitamin A",
    },
    "vitamina b1": {
        "synonyms": [
            "vitamin b1",
            "vitamina b1",
            "vitaminas b1",
            "tiamina",
        ],
        "exact_term": False,
        "brazil": "vitamina B1",
        "united_states": "vitamin B1",
    },
    "vitamina b10": {
        "synonyms": [
            "vitamin b10",
            "vitamina b10",
            "vitaminas b10",
            "paraaminobenzoico",
        ],
        "exact_term": False,
        "brazil": "vitamina B10",
        "united_states": "vitamin B10",
    },
    "vitamina b11": {
        "synonyms": [
            "vitamin b11",
            "vitamina b11",
            "vitaminas b11",
            "salicilico",
        ],
        "exact_term": False,
        "brazil": "vitamina B11",
        "united_states": "vitamin B11",
    },
    "vitamina b12": {
        "synonyms": [
            "vitamin b12",
            "vitamina b12",
            "vitaminas b12",
            "cobalamina",
        ],
        "exact_term": False,
        "brazil": "vitamina B12",
        "united_states": "vitamin B12",
    },
    "vitamina b13": {
        "synonyms": [
            "vitamin b13",
            "vitamina b13",
            "vitaminas b13",
            "orotico",
        ],
        "exact_term": False,
        "brazil": "vitamina B13",
        "united_states": "vitamin B13",
    },
    "vitamina b15": {
        "synonyms": [
            "vitamin b15",
            "vitamina b15",
            "vitaminas b15",
            "pangamico",
        ],
        "exact_term": False,
        "brazil": "vitamina B15",
        "united_states": "vitamin B15",
    },
    "vitamina b17": {
        "synonyms": [
            "vitamin b17",
            "vitamina b17",
            "vitaminas b17",
            "amigdalina",
        ],
        "exact_term": False,
        "brazil": "vitamina B17",
        "united_states": "vitamin B17",
    },
    "vitamina b2": {
        "synonyms": [
            "vitamin b2",
            "vitamina b2",
            "vitaminas b2",
            "riboflavina",
        ],
        "exact_term": False,
        "brazil": "vitamina B2",
        "united_states": "vitamin B2",
    },
    "vitamina b22": {
        "synonyms": [
            "vitamin b22",
            "vitamina b22",
            "vitaminas b22",
            "ratanhia",
        ],
        "exact_term": False,
        "brazil": "vitamina B22",
        "united_states": "vitamin B22",
    },
    "vitamina b3": {
        "synonyms": [
            "vitamin b3",
            "vitamina b3",
            "vitaminas b3",
            "niacina",
        ],
        "exact_term": False,
        "brazil": "vitamina B3",
        "united_states": "vitamin B3",
    },
    "vitamina b4": {
        "synonyms": [
            "vitamin b4",
            "vitamina b4",
            "vitaminas b4",
            "adenina",
        ],
        "exact_term": False,
        "brazil": "vitamina B4",
        "united_states": "vitamin B4",
    },
    "vitamina b5": {
        "synonyms": [
            "vitamin b5",
            "vitamina b5",
            "vitaminas b5",
            "pantotenico",
        ],
        "exact_term": False,
        "brazil": "vitamina B5",
        "united_states": "vitamin B5",
    },
    "vitamina b6": {
        "synonyms": [
            "vitamin b6",
            "vitamina b6",
            "vitaminas b6",
            "piridoxina",
        ],
        "exact_term": False,
        "brazil": "vitamina B6",
        "united_states": "vitamin B6",
    },
    "biotina": {
        "synonyms": [
            "biotin",
            "vitamina b7",
            "vitaminas b7",
            "biotina",
            "vitamina h",
        ],
        "exact_term": False,
        "brazil": "vitamina B7",
        "united_states": "biotin",
    },
    "vitamina b8": {
        "synonyms": [
            "vitamin b8",
            "vitamina b8",
            "vitaminas b8",
            "inositol",
        ],
        "exact_term": False,
        "brazil": "vitamina B8",
        "united_states": "vitamin B8",
    },
    "vitamina b9": {
        "synonyms": [
            "vitamin b9",
            "vitamina b9",
            "vitaminas b9",
            "folico",
        ],
        "exact_term": False,
        "brazil": "vitamina B9",
        "united_states": "vitamin B9",
    },
    "vitamina c": {
        "synonyms": [
            "vitamin c",
            "vitamina c",
            "vitaminas c",
            "c3",
            "C3",
            "ascorbico",
            "ascorbato",
            "ascorbila",
            "ácido ascórbico",
            "vitamina C",
            "ácido L-ascórbico",
            "L-ascorbico",
            "L-ascorbato",
            "L-ascorbila",
        ],
        "exact_term": False,
        "brazil": "vitamina C",
        "united_states": "vitamin C",
    },
    "vitamina d": {
        "synonyms": [
            "vitamin d",
            "vitamina d",
            "vitaminas d",
            "calciferol",
            "colecalciferol",
            "ergocalciferol",
            "vitamina d",
            "ácido calciferólico",
            "D3",
            "d3",
            "D2",
            "d2",
        ],
        "exact_term": True,
        "brazil": "vitamina D",
        "united_states": "vitamin D",
    },
    "vitamina e": {
        "synonyms": [
            "vitamin e",
            "vitamina e",
            "vitaminas e",
            "tocoferol",
            "tocoquinona",
            "vitamina E",
            "d-alfa-tocoferol",
            "dl-tocoferol",
        ],
        "exact_term": False,
        "brazil": "vitamina E",
        "united_states": "vitamin E",
    },
    "vitamina f": {
        "synonyms": [
            "vitamin f",
            "vitamina f",
            "vitaminas f",
            "graxos essenciais",
            "ácidos graxos essenciais",
        ],
        "exact_term": False,
        "brazil": "vitamina F",
        "united_states": "vitamin F",
    },
    "vitamina g": {
        "synonyms": [
            "vitamin g",
            "vitamina g",
            "vitaminas g",
            "monofosfato de nicotinamida",
            "nicotinamida monofosfato",
        ],
        "exact_term": False,
        "brazil": "vitamina G",
        "united_states": "vitamin G",
    },
    "vitamina j": {
        "synonyms": [
            "vitamin j",
            "vitamina j",
            "vitaminas j",
            "lipoico",
            "ácido lipoico",
        ],
        "exact_term": False,
        "brazil": "vitamina J",
        "united_states": "vitamin J",
    },
    "vitamina k": {
        "synonyms": [
            "vitamin k",
            "vitamina k",
            "vitaminas k",
            "filoquinona",
            "vitamina K",
            "fitoquinona",
        ],
        "exact_term": False,
        "brazil": "vitamina K",
        "united_states": "vitamin K",
    },
    "vitamina k1": {
        "synonyms": [
            "vitamin k1",
            "vitamina k1",
            "vitaminas k1",
            "fitoquinona",
            "phylloquinona",
        ],
        "exact_term": False,
        "brazil": "vitamina K1",
        "united_states": "vitamin K1",
    },
    "vitamina k2": {
        "synonyms": [
            "vitamin k2",
            "vitamina k2",
            "vitaminas k2",
            "menaquinona",
            "MK-7",
            "MK-4",
        ],
        "exact_term": False,
        "brazil": "vitamina K2",
        "united_states": "vitamin K2",
    },
    "vitamina k7": {
        "synonyms": [
            "vitamin k7",
            "vitamina k7",
            "vitaminas k7",
            "mk7",
            "menaquinona-7",
        ],
        "exact_term": False,
        "brazil": "vitamina K7",
        "united_states": "vitamin K7",
    },
    "vitamina q": {
        "synonyms": [
            "coenzyme q10",
            "vitamina q",
            "vitaminas q",
            "coenzima q10",
            "q10",
            "ubiquinona",
            "ubiquinol",
        ],
        "exact_term": False,
        "brazil": "coenzima q10",
        "united_states": "coenzyme Q10",
    },
    "wafer": {
        "synonyms": [
            "wafer",
            "wafer",
        ],
        "exact_term": False,
        "brazil": "wafer",
        "united_states": "wafer",
    },
    "waxymaize": {
        "synonyms": [
            "waxy maize",
            "waxymaize",
            "waxy maize",
            "amido de milho",
        ],
        "exact_term": False,
        "brazil": "waxymaize",
        "united_states": "waxy maize",
    },
    "whey": {
        "synonyms": [
            "whey",
            "whey",
            "soro do leite",
            "soro de leite",
        ],
        "exact_term": False,
        "brazil": "whey",
        "united_states": "whey",
    },
    "xylitol": {
        "synonyms": [
            "xylitol",
            "xylitol",
            "xilitol",
            "adocante",
            "adocante",
        ],
        "exact_term": False,
        "brazil": "xilitol",
        "united_states": "xylitol",
    },
    "zeaxantina": {
        "synonyms": [
            "zeaxanthin",
            "zeaxantina",
        ],
        "exact_term": False,
        "brazil": "zeaxantina",
        "united_states": "zeaxanthin",
    },
    "zinco": {
        "synonyms": [
            "zinc",
            "zinco",
        ],
        "exact_term": False,
        "brazil": "zinco",
        "united_states": "zinc",
    },
    "selenio": {
        "synonyms": [
            "selenium",
            "selenio",
            "seleni",
        ],
        "exact_term": False,
        "brazil": "selênio",
        "united_states": "selenium",
    },
    "zma": {
        "synonyms": [
            "zma",
            "zma",
        ],
        "exact_term": False,
        "brazil": "ZMA",
        "united_states": "ZMA",
    }
}

SUPPLEMENT_COMPONENT_LIST = {k: v for k, v in SUPPLEMENT_COMPONENT_LIST.items() if k not in WORDLIST_FLAVOR}
SUPPLEMENT_COMPONENT_LIST.update(WORDLIST_FLAVOR)

SUPPLEMENT_COMPONENT_LIST = {k: v for k, v in SUPPLEMENT_COMPONENT_LIST.items() if k not in WORDLIST_FORMAT}
SUPPLEMENT_COMPONENT_LIST.update(WORDLIST_FORMAT)

WORDLIST = {
    "supplement": SUPPLEMENT_COMPONENT_LIST,
}