jobs = {
    "essentialnutrition": {"name": "21st Century"},
    "twenty_first_century": {"name": "21st Century"},
    "three_vs_nutrition": {"name": "3VS Nutrition"},
    "four_plus_nutrition": {"name": "4 Plus Nutrition"},
    "absolut_nutrition": {"name": "Absolut Nutrition"},
    "adaptogen_science": {"name": "Adaptogen Science"},
    "airon": {"name": "Airon"},
    "alkans_pharma": {"name": "Alkans Pharma"},
    "alterative_pharma": {"name": "Alterative Pharma"},
    "amendoita": {"name": "Amendoita"},
    "arnold_nutrition": {"name": "Arnold Nutrition"},
    "athletica_nutrition": {"name": "Athletica Nutrition"},
    "atlhetica_clinical_series": {"name": "Atlhetica Clinical Series"},
    "atlhetica_nutrition": {"name": "Atlhetica Nutrition"},
    "banana_brasil": {"name": "Banana Brasil"},
    "belive": {"name": "Belive"},
    "biohgen": {"name": "Biohgen"},
    "blackskull": {"name": "Black Skull"},
    "blender_bottle": {"name": "Blender Bottle"},
    "blk_performance": {"name": "BLK Performance"},
    "body_nutry": {"name": "Body Nutry"},
    "bodyaction": {"name": "BodyAction"},
    "bodybuilders": {"name": "BodyBuilders"},
    "bold": {"name": "Bold"},
    "bpi_sports": {"name": "BPI Sports"},
    "brn_foods": {"name": "BRN Foods"},
    "bsn": {"name": "BSN"},
    "caffeine_army": {"name": "Caffeine Army"},
    "carob_house": {"name": "Carob House"},
    "catarinense_pharma": {"name": "Catarinense Pharma"},
    "cellucor": {"name": "Cellucor"},
    "champion_nutrition": {"name": "Champion Nutrition"},
    "chocolife": {"name": "Chocolife"},
    "cimed": {"name": "Cimed"},
    "clean_whey": {"name": "Clean Whey"},
    "cloma_pharma": {"name": "Cloma Pharma"},
    "copra": {"name": "Copra"},
    "cret_turbo": {"name": "Cret Turbo"},
    "cytosport": {"name": "CytoSport"},
    "dark_lab": {"name": "Dark Lab"},
    "darkness": {"name": "Darkness"},
    "demons_labs": {"name": "Demons Labs"},
    "desincha": {"name": "Desinchá"},
    "dr_peanut": {"name": "Dr. Peanut"},
    "dux_nutrition": {"name": "Dux Nutrition"},
    "dymatize": {"name": "Dymatize"},
    "eas": {"name": "EAS"},
    "el_shaddai": {"name": "El Shaddai"},
    "elementopuro": {"name": "ElementoPuro"},
    "elements": {"name": "Elements"},
    "essential_nutrition": {"name": "Essential Nutrition"},
    "eurofarma": {"name": "Eurofarma"},
    "fit_li": {"name": "Fit Li"},
    "fitmark": {"name": "FitMark"},
    "fitoway_labs": {"name": "Fitoway Labs"},
    "ftw": {"name": "FTW"},
    "furious_nutrition": {"name": "Furious Nutrition"},
    "gaab": {"name": "Gaab"},
    "gas": {"name": "GAS"},
    "gat": {"name": "GAT"},
    "generic_labs": {"name": "Generic Labs"},
    "go_nutrition": {"name": "GO Nutrition"},
    "grings": {"name": "Grings"},
    "growth_supplements": {"name": "Growth Supplements"},
    "gu": {"name": "GU"},
    "hammer_nutrition": {"name": "Hammer Nutrition"},
    "harbinger": {"name": "Harbinger"},
    "hart's": {"name": "Hart's"},
    "hass": {"name": "Hass"},
    "henger": {"name": "Henger"},
    "inove_nutrition": {"name": "Inove Nutrition"},
    "integralmedica": {"name": "Integralmédica"},
    "intlab": {"name": "Intlab"},
    "iridium_labs": {"name": "Iridium Labs"},
    "jasmine": {"name": "Jasmine"},
    "jay_cutler_nutrition": {"name": "Jay Cutler Nutrition"},
    "jm_encapsule": {"name": "Jm Encapsule"},
    "konjac_massa_mf": {"name": "Konjac Massa MF"},
    "la_ganexa": {"name": "La Ganexa"},
    "la_pianezza": {"name": "La Pianezza"},
    "labrada": {"name": "Labrada"},
    "lavitan": {"name": "Lavitan"},
    "leveza_beauty": {"name": "Leveza Beauty"},
    "loja_do_suplemento": {"name": "Loja do Suplemento"},
    "mais_pura": {"name": "Mais Pura"},
    "max_titanium": {"name": "Max Titanium"},
    "melatz": {"name": "Melatz"},
    "monsterfeed": {"name": "Monsterfeed"},
    "mrs_taste": {"name": "Mrs Taste"},
    "mrs_dash": {"name": "Mrs. Dash"},
    "multimarcas": {"name": "Multimarcas"},
    "muscle_infusion": {"name": "Muscle Infusion"},
    "muscle_pharm": {"name": "Muscle Pharm"},
    "musclemeds": {"name": "MuscleMeds"},
    "muscletech": {"name": "MuscleTech"},
    "muwiz": {"name": "Muwiz"},
    "my_suplementos": {"name": "My Suplementos"},
    "myprotein": {"name": "Myprotein"},
    "natuforme": {"name": "Natuforme"},
    "natures_best": {"name": "Nature's Best"},
    "natureza": {"name": "Natureza"},
    "naturovos": {"name": "NaturOvos"},
    "new_millen": {"name": "New Millen"},
    "new_nutrition": {"name": "New Nutrition"},
    "novo_easy_protein": {"name": "Novo Easy Protein"},
    "nutrabolics": {"name": "Nutrabolics"},
    "nutrata": {"name": "Nutrata"},
    "nutrex": {"name": "Nutrex"},
    "nutrify": {"name": "Nutrify"},
    "nutrilibrium": {"name": "Nutrilibrium"},
    "only4": {"name": "Only4"},
    "optimum_nutrition": {"name": "Optimum Nutrition"},
    "p28": {"name": "P28"},
    "pacific_health": {"name": "Pacific Health"},
    "performance_nutrition": {"name": "Performance nutrition"},
    "pornfit": {"name": "Pornfit"},
    "power_one": {"name": "Power One"},
    "power_supplements": {"name": "Power Supplements"},
    "prescription_labs_usa": {"name": "Prescription Labs USA"},
    "pretorian": {"name": "Pretorian"},
    "pro_healthy_laboratorios": {"name": "Pro Healthy Laboratórios"},
    "pro_supps": {"name": "Pro Supps"},
    "probiotica": {"name": "Probiótica"},
    "profit_labs": {"name": "Profit Labs"},
    "pura_vida": {"name": "Pura Vida"},
    "qnt": {"name": "QNT"},
    "quest_nutrition": {"name": "Quest Nutrition"}
}
